---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install -n --prefer-dist --no-progress

      - name: Tests
        run: ./vendor/bin/phpunit tests
        # run: mkdir -p ~/phpunit
        # run: ./vendor/bin/phpunit  --coverage-clover=~/phpunit/coverage.xml --coverage-html ~/phpunit/html --log-junit ~/phpunit/junit.xml tests
