name: delete_branch

on:
  pull_request:
    types: [merged, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Delete merged branch
      uses: SvanBoxel/delete-merged-branch@v1.3.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
